"""Criando tabelas iniciais

Revision ID: 07f78d41dbad
Revises: 
Create Date: 2025-11-30 19:11:05.102305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07f78d41dbad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('escola',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('ano_inauguracao', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fabricante',
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=True),
    sa.PrimaryKeyConstraint('cnpj')
    )
    op.create_table('coordenador',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('equipamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('localizacao', sa.String(length=100), nullable=True),
    sa.Column('condicao', sa.String(length=50), nullable=True),
    sa.Column('data_compra', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id_fabricante', sa.String(length=14), nullable=True),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id'], ),
    sa.ForeignKeyConstraint(['id_fabricante'], ['fabricante.cnpj'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professor',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('situacao', sa.String(length=50), nullable=True),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('plano_aula',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id_professor', sa.Integer(), nullable=False),
    sa.Column('id_coordenador', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_coordenador'], ['coordenador.matricula'], ),
    sa.ForeignKeyConstraint(['id_professor'], ['professor.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('emprestimo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('id_escola', sa.Integer(), nullable=False),
    sa.Column('id_equipamento', sa.Integer(), nullable=False),
    sa.Column('id_plano_aula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_equipamento'], ['equipamento.id'], ),
    sa.ForeignKeyConstraint(['id_escola'], ['escola.id'], ),
    sa.ForeignKeyConstraint(['id_plano_aula'], ['plano_aula.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitacao',
    sa.Column('id_servidor', sa.Integer(), nullable=False),
    sa.Column('id_emprestimo', sa.Integer(), nullable=False),
    sa.Column('id_coordenador', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_coordenador'], ['coordenador.matricula'], ),
    sa.ForeignKeyConstraint(['id_emprestimo'], ['emprestimo.id'], ),
    sa.ForeignKeyConstraint(['id_servidor'], ['administrador.matricula'], ),
    sa.PrimaryKeyConstraint('id_servidor', 'id_emprestimo', 'id_coordenador')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitacao')
    op.drop_table('emprestimo')
    op.drop_table('plano_aula')
    op.drop_table('professor')
    op.drop_table('equipamento')
    op.drop_table('coordenador')
    op.drop_table('fabricante')
    op.drop_table('escola')
    op.drop_table('categoria')
    op.drop_table('administrador')
    # ### end Alembic commands ###
