"""baseline inicial

Revision ID: 0ab9a318f7f9
Revises: 
Create Date: 2025-11-30 18:20:15.025812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0ab9a318f7f9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('servidor_adm',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.drop_table('administrador')
    op.add_column('coordenador', sa.Column('id', sa.Integer(), nullable=True))
    op.alter_column('coordenador', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('coordenador_ibfk_1'), 'coordenador', type_='foreignkey')
    op.create_foreign_key(None, 'coordenador', 'escola', ['id'], ['id'])
    op.drop_column('coordenador', 'id_escola')
    op.alter_column('emprestimo', 'quantidade',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('emprestimo', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('equipamento', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('equipamento', 'id_fabricante',
               existing_type=mysql.CHAR(length=14),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('equipamento', 'id_categoria',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('escola', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('escola', 'uf',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('escola', 'ano_inauguracao',
               existing_type=mysql.YEAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('fabricante', 'cnpj',
               existing_type=mysql.CHAR(length=14),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('fabricante', 'uf',
               existing_type=mysql.CHAR(length=2),
               type_=sa.String(length=2),
               existing_nullable=True)
    op.alter_column('fabricante', 'telefone',
               existing_type=mysql.CHAR(length=11),
               type_=sa.String(length=11),
               existing_nullable=True)
    op.add_column('plano_aula', sa.Column('id_coordenador', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'plano_aula', 'coordenador', ['id_coordenador'], ['matricula'])
    op.alter_column('professor', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('professor', 'id_escola',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('solicitacao_ibfk_1'), 'solicitacao', type_='foreignkey')
    op.create_foreign_key(None, 'solicitacao', 'servidor_adm', ['id_servidor'], ['matricula'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'solicitacao', type_='foreignkey')
    op.create_foreign_key(op.f('solicitacao_ibfk_1'), 'solicitacao', 'administrador', ['id_servidor'], ['matricula'])
    op.alter_column('professor', 'id_escola',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('professor', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(None, 'plano_aula', type_='foreignkey')
    op.drop_column('plano_aula', 'id_coordenador')
    op.alter_column('fabricante', 'telefone',
               existing_type=sa.String(length=11),
               type_=mysql.CHAR(length=11),
               existing_nullable=True)
    op.alter_column('fabricante', 'uf',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=True)
    op.alter_column('fabricante', 'cnpj',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=14),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('escola', 'ano_inauguracao',
               existing_type=sa.Integer(),
               type_=mysql.YEAR(),
               existing_nullable=True)
    op.alter_column('escola', 'uf',
               existing_type=sa.String(length=2),
               type_=mysql.CHAR(length=2),
               existing_nullable=True)
    op.alter_column('escola', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('equipamento', 'id_categoria',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('equipamento', 'id_fabricante',
               existing_type=sa.Integer(),
               type_=mysql.CHAR(length=14),
               nullable=False)
    op.alter_column('equipamento', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('emprestimo', 'data_hora',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('emprestimo', 'quantidade',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('coordenador', sa.Column('id_escola', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'coordenador', type_='foreignkey')
    op.create_foreign_key(op.f('coordenador_ibfk_1'), 'coordenador', 'escola', ['id_escola'], ['id'])
    op.alter_column('coordenador', 'nome',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('coordenador', 'id')
    op.create_table('administrador',
    sa.Column('matricula', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('bairro', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('uf', mysql.CHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('matricula'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('servidor_adm')
    # ### end Alembic commands ###
